services:

  postgres:
    image: postgres:16
    container_name: article-postgres
    environment:
      POSTGRES_DB: articlesdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  article-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: article-service
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_USERNAME: appuser
      QUARKUS_DATASOURCE_PASSWORD: apppassword
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/articlesdb
    ports:
      - "8080:8080"

volumes:
  postgres-data: